version: '2'
services:
  jhipsterforsearch-app:
    image: jhipsterforsearch
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipsterforsearch-postgresql:5432/jhipsterforsearch
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 30303:30303
  jhipsterforsearch-postgresql:
    extends:
      file: postgresql.yml
      service: jhipsterforsearch-postgresql
